stages:
  - deploy

variables:
  GITHUB_REPO: "wanderword/Fabella-Engine-SDK-Node"

deploy_job:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y git
  - git checkout -b main
  - git remote add github https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
  - git push github main
  only:
    - main
