stages:
  - deploy

variables:
  GITHUB_REPO: "wanderword/Fabella-Engine-SDK-Node"

deploy_job:
  stage: deploy
  script:
    - git remote add github https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
    - git push github $CI_COMMIT_REF_NAME:main
  only:
    - main  # Adjust the branch as needed
