name: 'Git setup and authentication'
description: 'Reusable step to setup and authenticate git for jobs.'
runs:
  using: "composite"
  steps: 
    - name: Configure Git Authentication
      shell: bash
      run: |
        git config --global user.email "dev@wanderword.net"
        git config --global user.name "Automated Release"
        git config --global http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ inputs.repo_access_token }} | base64)"
