name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  Prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@wanderword'
      - name: Set version
        id: set_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Current tag: $TAG_NAME"
          if [[ $TAG_NAME =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            VERSION=${TAG_NAME:1}
          elif [[ $TAG_NAME =~ ^[0-9]+\.[0-9]+$ ]]; then
            VERSION="$TAG_NAME.0"
          else
            echo "Tag name $TAG_NAME does not conform to SemVer (vMAJOR.MINOR.PATCH)"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_ENV
  Build:
    needs: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@wanderword'
      - uses: ./.github/actions/git-setup@v1
      - name: Set version
        run: npm version ${{ env.version }} --no-git-tag-version
      - name: Install dependencies
        run: yarn
      - name: Building package
        run: yarn build
      - name: Update .gitignore and commit changes
        run: |
          echo "Modifying .gitignore as needed"
          sed -i '/\/dist/d' .gitignore
          echo "/src" >> .gitignore
          echo "/.github" >> .gitignore
          git add .gitignore
          git commit -m "Update .gitignore to exclude src and .github"
      - name: Create new branch
        run: |
          echo "Setting git config"
          git config --global user.email "dev@wanderword.net"
          git config --global user.name "Automated Release"
          echo "Creating new branch"
          git switch -c publish/v${{ env.version }}
          git add .
          git commit -m "Publish package version: v${{ env.version }}"
      - name: Generate Changelog
        run: |
          npx auto-changelog --output CHANGELOG.md --tag-prefix '' --template keepachangelog
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
      - name: Push changes
        run: |
          git push --set-upstream origin "publish/v${{ env.version }}"
  Publish:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@wanderword'
      - uses: ./.github/actions/git-setup@v1
      - name: Pull publish repository
        run: |
          git fetch
          git checkout publish/v${{ env.version }}
      - name: Run Security Checks
        run: yarn audit
      - name: Dry Run Publish
        run: yarn publish --dry-run
      - name: Publish package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
